const roastLines: string[] = [
    "These motherfuckers think they can beat me",
    "Isn't it amazing how a tiny sperm cell can grow up into a unprofitable trader",
    "You deal damage like a rug pulls liquidity",
    "Nice TX hash, did your grandma sign that?",
    "Try again, faucet warrior",
    "I’ve seen meme coins with more utility than your attack",
    "Is that all your wallet can do?",
    "You must be farming for pity",
    "I’d bridge you back to web2 if I could",
    "Even USDT has more stability than your damage",
    "L2 noob spotted",
    "Call that a swap? I call it a joke",
    "Your wallet looks like it needs a bailout",
    "You mint excuses not attacks",
    "Try staking something useful like silence",
    "You attack like your RPC is throttled",
    "Back to Goerli, peasant",
    "I eat bots like you for gas fees",
    "I’ve felt more threat from an empty block",
    "That TX was slower than the ETH merge",
    "A DAO of toddlers could hit harder",
    "You probably got that TX hash from a faucet.",
    "I’ve seen more pressure from a soft fork.",
    "Is your wallet even verified, peasant?",
    "You’re more lost than Terra holders in 2022.",
    "My TPS is higher than your IQ.",
    "You must’ve staked your dignity.",
    "Your attack’s as useful as an expired airdrop.",
    "Try again when you’re not using testnet dust.",
    "Your NFT collection cries itself to sleep.",
    "I’ve met Solidity devs who type faster than you attack.",
    "You call that a snipe? Even bots would reject it.",
    "Are you farming damage or just Ls?",
    "This ain’t your Discord echo chamber, degen.",
    "Back to the memepool with you.",
    "You mint failure like it's going out of style.",
    "You sound like a DAO with no quorum.",
    "I’ve seen rugged projects put up more fight.",
    "Your wallet smells like airdrop beggar energy.",
    "Try submitting a TX that matters, clown.",
    "Is that attack rate-limited by your brain?",
    "You couldn’t hurt me if you bridged from L2.",
    "Your code’s more exploitable than my patience.",
    "Your on-chain activity screams cope.",
    "I eat 'ETH killers' for breakfast.",
    "Even a wrapped token hits harder.",
    "You minted that excuse too?",
    "This isn’t Farcaster, I can smell your engagement farming.",
    "Y’all ever considered staking your silence?",
    "You’re the reason multisigs exist.",
    "I’ve seen better performance from crypto influencers.",
    "You call that damage? I’ve seen dust tokens hit harder.",
    "My smart contract has better logic than your trades.",
    "You’re the reason ‘read-only’ exists.",
    "That TX was so weak it got front-run by a snail.",
    "Try again when gas isn’t wasted on your cope.",
    "Your wallet activity is a horror story.",
    "Even a cold wallet has more heat than you.",
    "You're not even rugged, you're pre-rugged.",
    "I've seen token burns with more impact.",
    "Did you sign that TX with a crayon?",
    "Your 'alpha' is just recycled Twitter threads.",
    "You mint Ls like it's your side hustle.",
    "Imagine bridging here just to embarrass yourself.",
    "You couldn’t stake a tent, let alone tokens.",
    "Even the mempool rejects your existence.",
    "You emit more hot air than a DAO proposal meeting.",
    "You’re more off-chain than a spreadsheet.",
    "I’ve seen honeypots with better traps.",
    "You transact like your private key is 123456.",
    "You’re the glitch in my matrix.",
    "Your strategy is just pressing ‘approve’ and praying.",
    "Even testnet faucets have more resistance.",
    "I bet your MetaMask has PTSD.",
    "Are you powered by snailchain?",
    "You're the typo in Solidity.",
    "My gas fees laugh at your attempts.",
    "You belong in a deprecated repo.",
    "You code like you’ve never seen StackOverflow.",
    "That swap had less slippage than your self-esteem.",
    "Go stake some self-awareness.",
    "Your contract reads like a phishing email.",
    "You couldn’t mint a thought.",
    "Your TPS is ‘Tears Per Second’.",
    "Even rug pullers have more commitment.",
    "You’re the missed block in my validator.",
    "Your airdrops are just dust collectors.",
    "I’ve seen better coordination from failed multisigs.",
    "Your wallet looks like a yield graveyard.",
    "Try deploying a better personality.",
    "You’re basically a failed DAO proposal.",
    "I’ve audited your moves. Result: REKT.",
    "You transact like you're still using AOL.",
    "Your TX speed is measured in ice ages.",
    "You use ‘hodl’ as a coping mechanism.",
    "You got out-gaslit by a protocol.",
    "You read the whitepaper like it’s fan fiction.",
    "You probably FOMO into presales with no website.",
    "Even my nonce thinks you're irrelevant.",
    "You’re the bug bounty nobody wants to fix.",
    "Try submitting a TX that doesn’t embarrass Ethereum.",
    "You're not early. You're irrelevant.",
    "You farm airdrops like it’s harvest season on chain.",
    "Did you even read the tokenomics or just clicked claim?",
    "If airdrops were skills, you’d still be bronze rank.",
    "You're one tx away from asking for seed funding—literally.",
    "You’re not early anon, you’re just desperate.",
    "You farm more forms than fields.",
    "That wallet screams “I signed up for everything and got nothing.”",
    "Airdrop hunter? More like hope-drop beggar.",
    "You stake your time and still earn zero.",
    "Even LayerZero ignores you.",
    "You’re the reason faucet limits exist.",
    "Keep farming, maybe you'll grow a clue.",
    "You filled 47 quests for $2—proud of you.",
    "You post more Zealy screenshots than real txs.",
    "You got rugged emotionally.",
    "Your harvest: 100 hours, $5, and regret.",
    "Your DEX score is 'pls sir, a crumb of governance.'",
    "You’re airdrop allergic to actual use cases.",
    "You click “Claim” like it's your 9–5.",
    "I’ve seen Discord bots more useful than your wallet.",
    "Your OpSec is a Google Sheet.",
    "Sybil-proof? You failed the tutorial.",
    "Keep claiming, legend—someone has to feed the whales.",
    "You batch claimed 12 airdrops and still missed the mainnet.",
    "All that effort, and the token is down 97%.",
    "You earn like a peasant, flex like a king.",
    "Your strategy: tag, retweet, and pray.",
    "Your entire net worth is 'coming soon.'",
    "Even the devs muted you on X.",
    "Real users interact with contracts—you interact with forms.",
    "You got the badge but missed the point.",
    "You farm testnets harder than you farm friendships.",
    "“Based and airdropped” isn’t a personality trait.",
    "Your L2 stash wouldn’t buy a domain name.",
    "Try holding conviction, not claim buttons.",
    "Your portfolio is 40 dust tokens and a dream.",
    "You hunted so hard, you forgot to live.",
    "You’re airdrop eligible for therapy.",
    "Your only alpha is 'connect wallet.'",
    "Gas fees fear you, but not for good reasons.",
    "You bridged for the XP, stayed for the cope.",
    "You got more form fatigue than chain history.",
    "You sybilled your dignity away.",
    "That wallet interaction history reads like a spam bot.",
    "You boosted Discord more than your bags.",
    "You got rate-limited by karma.",
    "You’re farming like it’s 2021 again.",
    "You camp snapshot like a sniper with no scope.",
    "You minted gas fees and despair.",
    "You rekt more Google Forms than contracts.",
    "You need airdrop therapy, not eligibility.",
    "They call you “whitelist warrior.”",
    "You minted FOMO.",
    "You sybil harder than you sleep.",
    "You cloned your wallet and your personality.",
    "Your best trade was a retweet.",
    "You’re more desperate than a Discord grind server.",
    "You got shadowbanned by the blockchain.",
    "You wrote essays in Zealy but failed basic DeFi.",
    "You’re eligible for disappointment, not tokens.",
    "Even your burner wallets gave up on you.",
    "You farmed the L3 questline and still got ghosted.",
    "You tweet like you’re paid in LARP.",
    "You added liquidity to cope.",
    "You built your self-worth on prelaunch speculation.",
    "Your bags are heavy with hopes and no unlocks.",
    "You sybil’d your soul.",
    "You chase snapshots like a degen chases red candles.",
    "You brag about testnet clout.",
    "Your contract interaction rate is 'mid.'",
    "You spin up more wallets than ideas.",
    "You follow more airdrop Twitter threads than charts.",
    "Your X account is 99% retweets and 1% disappointment.",
    "Even ZK can’t hide how broke you are.",
    "You’d trade your morals for an allowlist.",
    "You pray to DeFi gods for retroactive validation.",
    "Your wallet activity looks like noise on a scanner.",
    "You grind daily and gain dust.",
    "You claim faster than your thoughts load.",
    "You maxed every form but forgot to live.",
    "Your Zora mints are just wishful thinking.",
    "You fill more “why do you love us?” boxes than chats.",
    "You missed the token launch, but caught the rug.",
    "You show up for every drop, but never stick around.",
    "You’re more testnet than mainnet.",
    "Your Discord role means nothing here.",
    "You claim gas fees on your airdrop PnL.",
    "You got filtered by the airdrop contract.",
    "Your claim txs are just historical cope.",
    "You whisper “gm” hoping for karma points.",
    "Your mainnet footprint is dust and dreams.",
    "You earn XP in LARP, not liquidity.",
    "You grinded a hundred hours for 100 cents.",
    "Your bags are full of beta tokens.",
    "You sybil harder than you swap.",
    "You roleplayed a DAO member for a POAP.",
    "You qualify for everything but success.",
    "You mint, you grind, you fade.",
    "You chase yield like it owes you money.",
    "Your roadmap ends at 'airdrop when?'"
];

export default roastLines;
